### ISSUE TITLE
feature idea

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#10]
It would be great to have PL1-2 slider in the app. I think limited from down 10w to up115w would be great if that possible to release in yamdcc. Currently im setting those values directly in the bios, also it possible to do in the throttlestop uttility. So I thought if the performance modes can change power limits so that should be possible to set it in the ec table

**Comment by Sparronator9999** [comment]
Hi, this won't be done in YAMDCC for a few reasons:
1. I don't know how to manipulate MSRs (which is how other programs like ThrottleStop and QuickCPU set the CPU power limit)
2. Setting CPU power limits is a bit outside the scope of this project, as it is not an MSI-specific feature.
