### ISSUE TITLE
ui bug

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#11]
https://github.com/user-attachments/assets/c5976a8d-3e60-4e55-a811-475d6a79d02e

Load config doubling performance modes

**Comment by Sparronator9999** [comment]
How do these keep slipping through...

I'll fix this shortly.

**Comment by Sparronator9999** [comment]
The latest commit has fixed this issue.

**Comment by porkmanager** [comment]
Can confirm, u fixed that
