### ISSUE TITLE
Latest build(Template configs: the beginning) doesent works for me

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#16]
Hey!

https://github.com/user-attachments/assets/9ee2dfc8-f55f-4005-bf0e-d00a82a02e26

[yamdccsvc.exe.log](https://github.com/user-attachments/files/17126610/yamdccsvc.exe.log)

Just fresh install of latest build. I noticed that in the log mentioned about some configurator "Please run YAMDCC configurator and apply a config at least once."

**Comment by Sparronator9999** [comment]
That's weird, the service side seems to be working fine for me.

I did find some config app bugs that I have fixed in the latest commit.

**Comment by Sparronator9999** [comment]
Now I have to figure out why the crash dialog is broken...
