### ISSUE TITLE
Works on Vector GP78 HX 13V

### ISSUE THREAD

**Issue by Twisted6** [Sparronator9999/YAMDCC#18]
Thank you! No more 6200rpm fans as soon as temps hit 75c. I can actually play at more than 60 fps/low graphics on my 4080 :')

**Comment by Sparronator9999** [comment]
No problem!

Interestingly, we use YAMDCC for different purposes: I use it to apply a *more* aggressive fan curve to my laptop so it doesn't cook itself under high CPU load

**Comment by Sparronator9999** [comment]
> Additional note: This laptop also has RGB lights, so nokeylight config is required for this model (I also have a Vector GP78 HX 13V).

The README has been updated with this additional info. Thanks!
