### ISSUE TITLE
Latest one build CTD

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#19]
Crashing cuz cant find CurrentConfig.xml with clean installing. When that config present in prog.data folder yamdcc launching normal.
[crash-2024-09-29T13-47-24.txt](https://github.com/user-attachments/files/17179068/crash-2024-09-29T13-47-24.txt)

**Comment by Sparronator9999** [comment]
Hi, I can't reproduce this bug on my end, but I have a possible fix, which will be uploaded shortly after this message is written.

Briefly, I changed the way that the service checks for `CurrentConfig.xml`'s existence, hopefully fixing the bug.

**Comment by porkmanager** [comment]
Hey. I tried the latest build and previous bug still in on my side. Additional ive received a bug in the windows eventlog with this new one build instead a crashdump window in previous build

https://github.com/user-attachments/assets/65fa2b97-edb5-406b-bfc0-fb1cfb1a6f2c

**Comment by porkmanager** [comment]
Last build which launches/runs without any troubles on my pc is https://github.com/Sparronator9999/YAMDCC/actions/runs/11087389635
all subsequent ctd with CurrentConfig.xml arguments (only with clean instal)

**Comment by Sparronator9999** [comment]
Can you upload the files in `C:\ProgramData\Sparronator9999\YAMDCC`?

You may delete or move `LastConfig` (located in the above folder) before uploading to avoid leaking your PC's username if you want.

**Comment by Sparronator9999** [comment]
Okay, this is kind of embarrassing.

Turns out I removed (or otherwise forgot to implement) the check in the config app for `CurrentConfig.xml`'s existence.

A new build will be published shortly.

**Comment by porkmanager** [comment]
![image](https://github.com/user-attachments/assets/63669622-68f4-47e6-b6b0-9fdacd2d22eb)
The bug still in with the latest build. ;p
[yamdccsvc.exe.log](https://github.com/user-attachments/files/17274285/yamdccsvc.exe.log)
Win. event log:
[yamdcc.zip](https://github.com/user-attachments/files/17274300/yamdcc.zip)

**Comment by Sparronator9999** [comment]
Come on man, at least the config app isn't crashing anymore.

Anyways, I fixed the service crash in the latest commit.

**Comment by porkmanager** [comment]
Great! Now its fixed.

**Comment by Sparronator9999** [comment]
Nice.
