### ISSUE TITLE
Latest update breaks EC monitoring

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#27]
https://github.com/user-attachments/assets/f91c5a3d-8907-4584-8836-4e44d0cb1e3c
[yamdccsvc.exe.log](https://github.com/user-attachments/files/18194595/yamdccsvc.exe.log)

Tested latest build, it has issue with EC monitoring.

**Comment by Sparronator9999** [comment]
Well, now I know why I did things the way I did before (in terms of getting the fan RPM).

Fixed in latest commit.
