### ISSUE TITLE
Failed to read from EC register

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#28]
![image](https://github.com/user-attachments/assets/94cca703-ad16-4bba-b370-14a17d0922ed)
Launched yamdcc then enabled ECmonitoring and leave it runin in background for few minutes.
[yamdccsvc.exe.log](https://github.com/user-attachments/files/18266763/yamdccsvc.exe.log)

**Comment by porkmanager** [comment]
Sry. Found this issue in the Issues Megathread. I thought it has been fixed cuz last time i saw this issue along time ago.

**Comment by Sparronator9999** [comment]
Yep, duplicate of #21. See my [latest comment](https://github.com/Sparronator9999/YAMDCC/issues/21#issuecomment-2565064707) on that same issue.
