### ISSUE TITLE
ec monitoring

### ISSUE THREAD

**Issue by porkmanager** [Sparronator9999/YAMDCC#6]
![image](https://github.com/user-attachments/assets/9f5d9aa0-7e89-4b2f-8b23-c9fe35ac1b11)

Latest build for now. Doesent work ec monitoring

**Comment by Sparronator9999** [comment]
Damn it, it's happening to you as well.

I think it has something to do with the fact that the service is *trying* to crash, but isn't for some reason.

**Comment by Sparronator9999** [comment]
What's causing it is the latest update to add keyboard backlight support.

I'm assuming you haven't added the new `KeyLightConf` XML tag to your config yet (required for keyboard backlight to function), otherwise stuff breaks currently.

**Comment by porkmanager** [comment]
> If you go to the Extras tab, you'll notice a new greyed out option for adjusting the keyboard backlight (at least I hope it's greyed-out. If not, I swear...)

Yes it is greyed


> I'm assuming you haven't added the new `KeyLightConf` XML tag to your config yet (required for keyboard backlight to function), otherwise stuff breaks currently.

yep i didnt add to the config that value. And with your config MSI-GF63-Thin-11SC.xml ec still not working and kb baklit option also greyed out

**Comment by porkmanager** [comment]
> And with your config MSI-GF63-Thin-11SC.xml ec monitoring still not working and kb baklit option also greyed out

Oh, I have restarted the service and everything is working properly with your config. Thx bro for this great update!

**Comment by Sparronator9999** [comment]
Oh... I was just about to ask you to try the latest build that attempts to log more exceptions (which I think is what was happening before you updated).

I should probably fix the config system yet again so that this doesn't happen again...
